In [4]:
import numpy as np
from sklearn import *
import pandas as pd

# import train datasets and convert string to float
df_train = pd.read_csv("train.csv")
df_test = pd.read_csv("test.csv")


df_train.CONSIDERING_CHANGE_OF_PLAN.unique()
df_train.REPORTED_USAGE_LEVEL.unique()
df_train.REPORTED_SATISFACTION.unique()
df_train.REPORTED_SATISFACTION.unique()

df_train['COLLEGE'] = df_train['COLLEGE'].replace({"one": "1", "zero": "0"})
df_train['CONSIDERING_CHANGE_OF_PLAN'] = df_train['CONSIDERING_CHANGE_OF_PLAN'].replace({"no": "1", "considering": "2","perhaps": "3", "never_thought": "0", "actively_looking_into_it": '4'})
df_train['REPORTED_USAGE_LEVEL'] = df_train['REPORTED_USAGE_LEVEL'].replace({"little": "1", "very_little": "0","perhaps": "2", "very_high": "5", "high": '4',"avg": '3'})
df_train['REPORTED_SATISFACTION'] = df_train['REPORTED_SATISFACTION'].replace({"unsat": "1", "very_unsat": "0","very_sat": "4", "avg": "2", "sat": '3'})

df_test['COLLEGE'] = df_train['COLLEGE'].replace({"one": "1", "zero": "0"})
df_test['CONSIDERING_CHANGE_OF_PLAN'] = df_train['CONSIDERING_CHANGE_OF_PLAN'].replace({"no": "1", "considering": "2","perhaps": "3", "never_thought": "0", "actively_looking_into_it": '4'})
df_test['REPORTED_USAGE_LEVEL'] = df_train['REPORTED_USAGE_LEVEL'].replace({"little": "1", "very_little": "0","perhaps": "2", "very_high": "5", "high": '4',"avg": '3'})
df_test['REPORTED_SATISFACTION'] = df_train['REPORTED_SATISFACTION'].replace({"unsat": "1", "very_unsat": "0","very_sat": "4", "avg": "2", "sat": '3'})



df_train.to_csv('train2.csv', index=False)
df_test.to_csv('test2.csv', index=False)

df_test.head()

,COLLEGE,INCOME,OVERAGE,LEFTOVER,HOUSE,HANDSET_PRICE,OVER_15MINS_CALLS_PER_MONTH,AVERAGE_CALL_DURATION,REPORTED_SATISFACTION,REPORTED_USAGE_LEVEL,CONSIDERING_CHANGE_OF_PLAN
0,0,142806,202,0,264371,562,29,13,1,1,1
1,1,41532,66,45,619188,190,3,2,1,1,2
2,1,51919,191,61,986348,355,21,1,1,0,3
3,0,32732,0,0,255165,301,1,10,1,5,2
4,1,40412,0,0,246803,239,26,8,0,1,0

In [8]:
#df_train = pd.read_csv("train3.csv")
#df_test = pd.read_csv("test3.csv")
#df_target = pd.read_csv("test4.csv")

df_train = pd.read_csv("train2.csv")
df_test = pd.read_csv("test2.csv")

#selecting features
features = list(df_train.columns[:11])

X = df_train[features]
Y = df_train['LEAVE']
#y_test = df_target['LEAVE']

DTree = tree.DecisionTreeClassifier(class_weight=None,
                                    criterion='entropy',
                                    max_depth=6,#max_depth avoid overfitting
                                    max_features=None, #features number
                                    max_leaf_nodes=None,
                                    min_impurity_decrease=1e-06, #limit the length grow of the treeï¼Œ
                                    #if impurity<1e-06 then it will not have children.Be a leaf node.
                                    min_samples_leaf=1,
                                    min_samples_split=2,
                                    #min_samples_split or min_samples_leaf control the sample number on leaf
                                    random_state=None, splitter='best')
            
DTree = DTree.fit(X, Y)
predictions = DTree.predict(df_test)
print(predictions)

pd.DataFrame(predictions, columns=['LEAVE']).to_csv('prediction.csv')

#accuracy = DTree.score(X,Y)

#print(accuracy)


#metrics.classification_report(y_test,predictions)

[0 1 1 ..., 0 0 1]